### PR TITLE
unify usage of gocheck

### PR DESCRIPTION
**Pull request by elmacnifico**
I switched all tests over to use gocheck to have a more consistent look and feel.

### CODE REVIEW

**Comment by oschwald** [comment]
I think I'd prefer to go in the other direction and remove the use of gocheck in `reader_test.go`. gocheck doesn't seem to be under active development, and it is a bit of a pain to use with the standard test tooling.

**Comment by elmacnifico** [comment]
that would have been my plan b ;)
if i have some time today i'll make a pr.

**Comment by elmacnifico** [comment]
btw how would you feel about using smth like github.com/stretchr/testify/assert to reduce some of the error nil catching

**Comment by oschwald** [comment]
That'd be great! Testify sounds good.

**Pull request closed without merging**
