### PR TITLE
Added Traverse method

### PR DESCRIPTION
**Pull request by ErikDubbelboer**
Add a method to traverse the loaded database. I personally use this to enumerate the database to extract all possible ISP's from it.

If you want I can add a simple example.

### CODE REVIEW

**Comment by ErikDubbelboer** [comment]
Sorry it took so long. Please check the new version I just committed. It now uses an iterator and I added a test case.

**Comment by oschwald** [comment]
Thanks! This looks good. I might take a shot at making it process the subnets in order. It should be doable by switching to depth-first traversal.

**Comment by oschwald** [comment]
I made some minor tweaks to this in https://github.com/oschwald/maxminddb-golang/tree/traverse to traverse in order and also to return the subnet (`net.IPNet`) for the record rather than just the first IP.

**Comment by ErikDubbelboer** [comment]
That looks really good and quite a bit simpler :)

**Comment by oschwald** [comment]
Thanks. I'll merge it. I just want to add some additional tests. I'll hopefully get to it this weekend.

**Comment by oschwald** [comment]
Closing as this is in master already.

**Pull request closed without merging**
